### ISSUE TITLE
Support depth infinity

### ISSUE THREAD

**Issue by jonathan-neufeld-hs** [varnish/libvmod-softpurge#2]
AFAIK soft-purge only purges the precise resource at the current request URL.  What I would expect (and I believe is more consistent with the overall web) is that a PURGE of any URL would also result in a PURGE for all subsequent (descendant) URLs.  In other words, the following request

Given these URLs cached by Varnish:

/foo
/foo/blog
/foo/bar
/foo/bar/apple
/foo/bar/orange
/foo/bar/peas/grapes

The request:

PURGE /foo/bar

Should have the same effect as the following:

PURGE /foo/bar
PURGE /foo/bar/apple
PURGE /foo/bar/orange
PURGE /foo/bar/peas/grapes

This would be useful in scenarios where dependent URLs of any particular URL is not fully known.

**Comment by lkarsten** [comment]
You are looking for the other method of cache invalidation in varnish: bans.

**Comment by jonathan-neufeld-hs** [comment]
On the contrary, bans will block cached responses resulting in a poor user experience.  The benefit of soft-purge is that it will serve-up the old page until the new one becomes available.  What I would like is the ability to soft-purge multiple objects, preferably all objects, not just one.  Ideally soft-purge would have the same flexibility and be consistent with ban without actually blocking cached responses.

**Comment by lkarsten** [comment]
There were some work done on soft bans in 3.0, but that never got merged into mainline. I believe the fork is still floating around on github.

What you most likely want, is to have someone merge the softpurge mechanism into libvmod-xkey. I believe the work was done for an earlier Varnish version, but I'm not sure if that has reached the released version yet.
